version: "3"

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: backend_test
    ports:
      - '4306:3306'
    networks:
      - my-network
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - '9000:9000'
    networks:
      - my-network
    volumes:
      - ./:/var/www/backend_test
    depends_on:
      - database
    command: >
      bash -c "
        php bin/console doctrine:database:create ;
        php bin/console doctrine:migrations:migrate ;
        php bin/console doctrine:database:create --env=test ;
        php bin/console doctrine:migrations:migrate --env=test"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    networks:
      - my-network
    volumes:
      - ./:/var/www/backend_test
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

# Define networks
networks:
  my-network:
